dist: xenial  # required for Python >= 3.7
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "nightly"
matrix:
  allow_failures:
    - python: "nightly"
install:
  - "pip install --editable .[with_everything]"
  - "pip install safety pipenv numpy tzlocal nose coverage coveralls py -U"
  - "pip freeze | safety check --stdin"
script:
  - "nosetests -s --with-coverage --cover-inclusive --cover-package=prospector tests/"
  - "mv .coverage .coverage.x"
  - "coverage run --parallel-mode prospector/run.py || true"
  - "coverage combine"
  - "coverage report --show-missing"
after_success:
  - |
      prospector -0
      coveralls
notifications:
  email:
    on_failure: change
    on_success: never
