name: tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6.1.0
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install poetry
      - run: poetry install --all-extras --all-groups
      # - run: poetry show --all
      # - run: poetry show --outdated
      # - run: poetry show --tree
      - name: Install test profile used in the tests
        run: poetry run pip install tests/prospector-profile-test/
      - run: poetry run pytest --benchmark-disable --cov --cov-report= tests/
      - name: Run Prospector checks
        run: poetry run prospector --output=pylint
      - name: Check that Prospector can run
        run: |
          echo "Checking prospector can run; don't care about messages found, only that it runs successfully"
          poetry run prospector --quiet --zero-exit
          echo "Prospector ran successfully."
      - name: Check packaging
        run: |
          echo "Building packages"
          rm -rf dist/
          poetry build
          echo "Validating packages"
          poetry run twine check dist/*
          echo "Packages build and valdiate successfully."
