name: tests
on: [push, pull_request]
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']
    steps:
      - uses: actions/checkout@v3
      - run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'
      - run: poetry install -E with_everything
      # - run: poetry show --all
      # - run: poetry show --outdated
      # - run: poetry show --tree
      - run: poetry run pytest --benchmark-disable --cov --cov-report= tests/
      - name: Check that Prospector can run
        run: |
          echo "Checking prospector can run; don't care about messages found, only that it runs successfully"
          poetry run prospector --quiet --zero-exit
          echo "Prospector ran successfully."
      - name: Check packaging
        run: |
          echo "Building packages"
          rm -rf dist/
          poetry build
          echo "Validating packages"
          poetry run twine check dist/*
          echo "Packages build and valdiate successfully."
